services:
  stocks:
    build: 
      context: .
      dockerfile: ./apps/stocks/Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev stocks
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev auth
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"